# Generated by Django 3.0.5 on 2020-04-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contest', models.CharField(max_length=200)),
                ('problem_statement', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('attempt_count', models.IntegerField(default=0)),
                ('ac_count', models.IntegerField(default=0)),
                ('player_a', models.CharField(max_length=200)),
                ('player_b', models.CharField(max_length=200)),
            ],
        ),
    ]
