# Generated by Django 3.0.5 on 2020-04-12 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='name',
            new_name='title',
        ),
    ]
