# Generated by Django 3.0.5 on 2020-04-12 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20200412_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='author',
        ),
    ]
