# Generated by Django 3.0.5 on 2020-04-13 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_game_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ac_count',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_a',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player_b',
        ),
    ]
