# Generated by Django 3.0.5 on 2020-04-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20200413_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='how_to_play',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
